imu:
  port: /dev/ttyACM0
  bps: 460800
camera:
  ids:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14
  index_map:
    0: 0
    1: 2
    2: 4
    3: 8
    4: 6
    5: 12
    6: 10
    7: 14
  width: 640
  height: 480
  display:
    max_cols: 4
  extrinsics:
    cam0:
      physical_id: 0
      translation:
      - -0.2215
      - -0.017729
      - 0.078699
      rotation:
      - 0.01371057
      - 0.191242
      - -0.00803644
      - 0.98141425
      n_samples: 76
    cam1:
      physical_id: 1
      translation:
      - -0.198876
      - -0.022879
      - 0.06769
      rotation:
      - 0.00810946
      - 0.19207212
      - -0.00870314
      - 0.98130871
      n_samples: 75
    cam2:
      physical_id: 2
      translation:
      - -0.028103
      - 0.002174
      - 0.001922
      rotation:
      - 0.03050023
      - 0.00533526
      - -0.00068329
      - 0.99952029
      n_samples: 77
    cam3:
      physical_id: 3
      translation:
      - 0.0
      - 0.0
      - 0.0
      rotation:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      n_samples: 73
    cam4:
      physical_id: 4
      translation:
      - -0.022097
      - -0.039569
      - -0.003469
      rotation:
      - -0.15631201
      - -0.01298685
      - -0.00173516
      - 0.98762082
      n_samples: 78
    cam5:
      physical_id: 5
      translation:
      - -0.000462
      - -0.040253
      - -0.003014
      rotation:
      - -0.16146386
      - -0.01305272
      - -0.00168269
      - 0.98679087
      n_samples: 76
    cam6:
      physical_id: 6
      translation:
      - 0.169626
      - -0.028481
      - 0.074528
      rotation:
      - -0.01123324
      - -0.18880554
      - -0.00861776
      - 0.98191243
      n_samples: 76
    cam7:
      physical_id: 7
      translation:
      - 0.194742
      - -0.03336
      - 0.078528
      rotation:
      - 0.00589217
      - -0.17952832
      - -0.00385683
      - 0.9837276
      n_samples: 76
