imu:
  port: /dev/ttyACM0
  bps: 460800
camera:
  ids:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14
  index_map:
    0: 0
    1: 2
    2: 4
    3: 8
    4: 6
    5: 12
    6: 10
    7: 14
  width: 640
  height: 480
  display:
    max_cols: 4
    
  extrinsics:
    cam0:
      physical_id: 0
      translation:
      - -0.219424
      - -0.018262
      - 0.079163
      rotation:
      - 0.01394645
      - 0.19285843
      - -0.00785971
      - 0.98109599
      n_samples: 76
    cam1:
      physical_id: 1
      translation:
      - -0.197086
      - -0.022579
      - 0.068521
      rotation:
      - 0.0089944
      - 0.19414703
      - -0.0088054
      - 0.98089168
      n_samples: 76
    cam2:
      physical_id: 2
      translation:
      - -0.028858
      - 4.7e-05
      - 0.002331
      rotation:
      - 0.02685575
      - 0.00705388
      - -0.00021123
      - 0.99961441
      n_samples: 77
    cam3:
      physical_id: 3
      translation:
      - 0.0
      - 0.0
      - 0.0
      rotation:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      n_samples: 76
    cam4:
      physical_id: 4
      translation:
      - -0.022682
      - -0.041103
      - -0.002827
      rotation:
      - -0.15853139
      - -0.01220629
      - -0.00112063
      - 0.98727785
      n_samples: 78
    cam5:
      physical_id: 5
      translation:
      - 0.000248
      - -0.039918
      - -0.00243
      rotation:
      - -0.16157132
      - -0.0141291
      - -0.00148564
      - 0.98675877
      n_samples: 71
    cam6:
      physical_id: 6
      translation:
      - 0.168507
      - -0.027506
      - 0.074514
      rotation:
      - -0.00992447
      - -0.18957547
      - -0.00823324
      - 0.98178147
      n_samples: 76
    cam7:
      physical_id: 7
      translation:
      - 0.193229
      - -0.032017
      - 0.078433
      rotation:
      - 0.00673146
      - -0.18007826
      - -0.00265248
      - 0.98362568
      n_samples: 76
