imu:
  port: /dev/ttyACM0
  bps: 460800
camera:
  ids:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14
  index_map:
    0: 8
    1: 14
    2: 2
    3: 10
    4: 6
    5: 0
    6: 4
    7: 12
  width: 640
  height: 480
  display:
    max_cols: 4
  extrinsics:
    cam0:
      physical_id: 0
      translation:
      - -0.223485
      - -0.030203
      - 0.091945
      rotation:
      - 0.01837048
      - 0.23083496
      - 0.0030496
      - 0.9728147
      n_samples: 69
    cam1:
      physical_id: 1
      translation:
      - -0.201418
      - -0.033199
      - 0.080124
      rotation:
      - 0.01430786
      - 0.23067225
      - 0.0011318
      - 0.97292565
      n_samples: 69
    cam2:
      physical_id: 2
      translation:
      - -0.03074
      - -0.004154
      - 0.000369
      rotation:
      - 0.01584964
      - 0.00906934
      - -0.00078006
      - 0.99983295
      n_samples: 75
    cam3:
      physical_id: 3
      translation:
      - 0.0
      - 0.0
      - 0.0
      rotation:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      n_samples: 75
    cam4:
      physical_id: 4
      translation:
      - -0.008674
      - -0.051332
      - -0.002251
      rotation:
      - -0.17443205
      - -0.00058179
      - -0.00017172
      - 0.98466903
      n_samples: 76
    cam5:
      physical_id: 5
      translation:
      - -0.029834
      - -0.05436
      - -0.001775
      rotation:
      - -0.17536307
      - -0.0010915
      - -0.00075109
      - 0.98450294
      n_samples: 76
    cam6:
      physical_id: 6
      translation:
      - 0.161686
      - -0.031171
      - 0.084498
      rotation:
      - -0.00101639
      - 0.22402001
      - 0.00021668
      - -0.97458399
      n_samples: 75
    cam7:
      physical_id: 7
      translation:
      - 0.18678
      - -0.036507
      - 0.090321
      rotation:
      - -0.00751125
      - 0.2059253
      - -0.00813951
      - -0.97850503
      n_samples: 75
