imu:
  port: /dev/ttyACM0
  bps: 460800
camera:
  ids:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14
  index_map:
    0: 2
    1: 8
    2: 0
    3: 4
    4: 14
    5: 10
    6: 6
    7: 12
  width: 640
  height: 480
  display:
    max_cols: 4
  extrinsics:
    cam0:
      physical_id: 0
      translation:
      - -0.217588
      - -0.018921
      - 0.06997
      rotation:
      - 0.01088399
      - 0.18276651
      - -0.00872253
      - 0.9830574
      n_samples: 74
    cam1:
      physical_id: 1
      translation:
      - -0.193801
      - -0.027874
      - 0.065645
      rotation:
      - -0.00112247
      - 0.18900573
      - -0.00829555
      - 0.9819403
      n_samples: 70
    cam2:
      physical_id: 2
      translation:
      - -0.023759
      - -0.003035
      - 6.0e-05
      rotation:
      - 0.02099478
      - -0.00141667
      - 0.0001123
      - 0.99977858
      n_samples: 71
    cam3:
      physical_id: 3
      translation:
      - 0.0
      - 0.0
      - 0.0
      rotation:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      n_samples: 66
    cam4:
      physical_id: 4
      translation:
      - 0.001138
      - -0.050166
      - -0.003242
      rotation:
      - -0.17678913
      - -0.01440844
      - -0.00312332
      - 0.98413833
      n_samples: 76
    cam5:
      physical_id: 5
      translation:
      - -0.021411
      - -0.054817
      - -0.003269
      rotation:
      - -0.18026715
      - -0.01388991
      - -0.0037539
      - 0.98351245
      n_samples: 75
    cam6:
      physical_id: 6
      translation:
      - 0.170545
      - -0.02616
      - 0.074776
      rotation:
      - -0.00730689
      - -0.19293422
      - -0.00629915
      - 0.98116427
      n_samples: 63
    cam7:
      physical_id: 7
      translation:
      - 0.194349
      - -0.033595
      - 0.079753
      rotation:
      - 0.0037434
      - -0.1824121
      - -0.0023697
      - 0.98321218
      n_samples: 63
